In [1]:
import pandas as pd
import numpy as np

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [2]:
Hut_Paradise_values = Hut_Paradise_DF.values[4]
print(Hut_Paradise_values)

[40 33  1  6 20 16]


In [3]:
Hut_Paradise_values = Hut_Paradise_DF['4.Floor'].values
print(Hut_Paradise_values)

[ 5 12 10  3  6 13  8 21  5]


In [4]:
Hut_Paradise_values = Hut_Paradise_DF['2.Area'].values - Hut_Paradise_DF['6.Liv.Area'].values
print(Hut_Paradise_values)

[13 12 15 13 17  9 20 15 25]


In [5]:
viewing = [10, 20, 30, 15, 5, 40, 20, 8, 20]
Hut_Paradise_values = (Hut_Paradise_DF['5.Demo two weeks'] * viewing).sum()
print(Hut_Paradise_values)

1348


Дано 3 вектора:

In [6]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [7]:
res = (2*v) + (-3*w)
res

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [8]:
u = np.array([3, 0, 1, 1, 1])
res = np.array([-3, 14, 3, 4, 2])

dot_product = np.dot(u, res)
print(dot_product)

0


# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [9]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

In [51]:
Inc = Husband_Income, Wife_Income, Mother_In_Law_Income
df_income = pd.DataFrame(Inc)
A = df_income.values
A.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

In [55]:
Cons = Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption
df_consumption = pd.DataFrame(Cons)
B = df_consumption.values
B.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу , где доходы расположены по столбцам.

In [74]:
nalog = A.T * 0.87
nalog

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Вычислите матрицу P , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [77]:
P = nalog - B.T
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

Найти произведение матриц

In [79]:
A = np.array([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])

B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])

In [83]:
С = np.dot(A,B)
С

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])