In [168]:
import pandas as pd
import numpy as np

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [169]:
Hut_Paradise_values = Hut_Paradise_DF.values[4]
print(Hut_Paradise_values)

[40 33  1  6 20 16]


In [170]:
Hut_Paradise_values = Hut_Paradise_DF['4.Floor'].values
print(Hut_Paradise_values)

[ 5 12 10  3  6 13  8 21  5]


In [171]:
Hut_Paradise_values = Hut_Paradise_DF['2.Area'].values - Hut_Paradise_DF['6.Liv.Area'].values
print(Hut_Paradise_values)

[13 12 15 13 17  9 20 15 25]


In [172]:
viewing = [10, 20, 30, 15, 5, 40, 20, 8, 20]
Hut_Paradise_values = (Hut_Paradise_DF['5.Demo two weeks'] * viewing).sum()
print(Hut_Paradise_values)

1348


Дано 3 вектора:

In [173]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [174]:
res = (2*v) + (-3*w)
res

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [175]:
u = np.array([3, 0, 1, 1, 1])
res = np.array([-3, 14, 3, 4, 2])

dot_product = np.dot(u, res)
print(dot_product)

0


# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [176]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

In [177]:
Inc = Husband_Income, Wife_Income, Mother_In_Law_Income
df_income = pd.DataFrame(Inc)
A = df_income.values
A.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

In [178]:
Cons = Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption
df_consumption = pd.DataFrame(Cons)
B = df_consumption.values
B.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу , где доходы расположены по столбцам.

In [179]:
nalog = A.T * 0.87
nalog

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Вычислите матрицу P , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [180]:
P = nalog - B.T
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

Найти произведение матриц

In [181]:
A = np.array([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])

B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])

In [182]:
С = np.dot(A,B)
С

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

Даны матрица A и вектор х:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

In [183]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(A)
print('*****')
print(x)

[[ 5 -1  3  1  2]
 [-2  8  5 -1  1]]
*****
[1 2 3 4 5]


In [184]:
G = np.dot(A,x)
G

array([26, 30])

Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

In [185]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(A)
print('*****')
print(B)

[[1 9 8 5]
 [3 6 3 2]
 [3 3 3 3]
 [0 2 5 9]
 [4 4 1 2]]
*****
[[ 1 -1  0  1  1]
 [-2  0  2 -1  1]]


In [186]:
C = np.dot(B,A)
C

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Составьте матрицу , расположив векторы , ,  в строках. Найдите матрицу Грама  (матрицу скалярных произведений столбцов матрицы ) системы векторов , , .

Чему равна полученная матрица Грама ?

In [187]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [188]:
matrix = x, y, z
G = pd.DataFrame(matrix)
G.values
np.dot(G.T, G)

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.\
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.\
Count_DF = pd.DataFrame({\
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], \
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], \
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],\
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],\
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]\
    }, \
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']\
)\
Price_DF = pd.DataFrame({\
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], \
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], \
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],\
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],\
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] \
    }, \
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']\
)

In [189]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

In [190]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

# Доход по услугам (Count × Price)
income_per_service = Count_DF * Price_DF

# Умножение каждого столбца на соответствующую комиссию
income_for_salon = income_per_service * com  # Поэлементное умножение на вектор комиссий

print("Доход салона по стилистам:")
print(total_income)

Доход салона по стилистам:
Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64


Найдите вектор дохода стилистов.

In [201]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

# Доход по услугам (Count × Price)
income_per_service = Count_DF * Price_DF

# Умножение каждого столбца на соответствующую комиссию
income_for_salon = income_per_service * com  # Поэлементное умножение на вектор комиссий
income_per = income_per_service - income_for_salon
income_per.sum(axis=1)

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64