# Найдите матрицу, обратную матрице A.

In [4]:
import numpy as np

In [2]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [5]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

# Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])\
v2 = np.array([2, 0, 5, 1, 4])\
v3 = np.array([4, 0, 0, 4, 1])\
v4 = np.array([3, -4, 3, -1, -4])

In [6]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

## Найдите ранг системы векторов v1, v2, v3, v4. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [11]:
matrix_v = np.array([v1, v2, v3, v4]).T
np.linalg.matrix_rank(matrix_v)

np.int64(4)

## Найдите матрицу Грама системы векторов v1, v2, v3, v4:G=A.T A . В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [18]:
print('Матрица Грама:\n',matrix_v.T@matrix_v)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


## Найдите определитель матрицы Грама  системы v1, v2, v3, v4. Ответ округлите до целого числа.

In [24]:
print('Определитель матрицы Грама:\n', round(np.linalg.det(matrix_v.T@matrix_v)))

Определитель матрицы Грама:
 3716648


## Найдите обратную матрицу к матрице Грама G системы v1, v2, v3, v4. В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [32]:
print('Обратная к матрице Грама:\n',np.linalg.inv(matrix_v.T@matrix_v))

Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
